### ISSUE TITLE
New loading template

### ISSUE THREAD

**Issue by Billybobbonnet** [perak/kitchen-site#69]
Here is a quick change to add a centered loader instead of the loading text:

 /client/views/loading/loading.html

```html
<template name="loading">
 		 <div class="loading">
	    		<i class="fa fa-circle-o-notch fa-4x fa-spin"></i>
		</div>
</template>
```
and add this into  /client/styles/default/styles.less

```less
// **** LOADING ****
.loading {
  text-align: center;
  padding: 48px 0; // to avoid seing it top when loading main pages
  vertical-align:middle;
  i {
    color: @gray-lighter;
  }
}

```
